name: Despliegue Bot Metropol

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule:
    # Se ejecuta cada 6 horas (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */6 * * *'

jobs:
  run-metropol:
    runs-on: ubuntu-latest
    # Evita que se acumulen procesos si uno se queda trabado
    concurrency: 
      group: metropol-bot
      cancel-in-progress: true

    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar Dependencias
        run: |
          python -m pip install --upgrade pip
          pip install discord.py firebase-admin google-cloud-firestore python-dotenv

      - name: Ejecutar Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          python main.py
